Core_Proje/Controllers/PortfolioController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace Core_Proje.Controllers
{
    public class PortfolioController : Controller
    {
        PortfolioManager portfolioManager = new PortfolioManager(new EfPortfolioDal());
        public IActionResult Index()
        {
            var values = portfolioManager.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddPortfolio()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddPortfolio(Portfolio portfolio)
        {
            //fluent validation kuralları (portfoliovalidatorde tanımlanan şartların) kontrolü
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult results = validations.Validate(portfolio);
            if (results.IsValid) { 
            portfolioManager.TAdd(portfolio);
            return RedirectToAction("Index");
            }
            else
            {
                foreach(var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public IActionResult DeletePortfolio(int id)
        {
            var values = portfolioManager.TGetByID(id);
            portfolioManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditPortfolio(int id)
        {
            var values = portfolioManager.TGetByID(id);
            return View(values);

        }
        [HttpPost]
        public IActionResult EditPortfolio(Portfolio portfolio)
        {
            //fluent validation kuralları (portfoliovalidatorde tanımlanan şartların) kontrolü
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult results = validations.Validate(portfolio);
            if (results.IsValid)
            {
                portfolioManager.TUpdate(portfolio);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }
    }
}

Core_Proje/Views/Portfolio/AddPortfolio.cshtml
@model EntityLayer.Concrete.Portfolio
@{
    ViewData["Title"] = "AddPortfolio";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("AddPortfolio", "Portfolio", FormMethod.Post))
{
    <br />
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yeni Proje Ekle </p>
                <form class="forms-sample" method="post">
                    @Html.Label("Proje Başlığı")
                    @Html.TextBoxFor(x=>x.Name,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Name)
                    <br />
                    <label>Görsel1</label>
                    @Html.TextBoxFor(x=>x.ImageUrl,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ImageUrl)
                    <br />
                    <label>Görsel2</label>
                    @Html.TextBoxFor(x=>x.ImageUrl2,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ImageUrl2)
                    <br />
                    <label>Proje Url</label>
                    @Html.TextBoxFor(x=>x.ProjectUrl,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ProjectUrl)
                    <br />
                    <label>Resim1</label>
                    @Html.TextBoxFor(x=>x.Image1,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image1)
                    <br />
                    <label>Resim2</label>
                    @Html.TextBoxFor(x=>x.Image2,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image2)
                    <br />
                    <label>Resim3</label>
                    @Html.TextBoxFor(x=>x.Image3,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image3)
                    <br />
                    <label>Resim4</label>
                    @Html.TextBoxFor(x=>x.Image4,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image4)
                    <br />
                    <label>Platform</label>
                    @Html.TextBoxFor(x=>x.Platform,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Platform)
                    <br />
                    <label>Tutar</label>
                    @Html.TextBoxFor(x=>x.Price,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Price)
                    <br />
                    <label>Tamamlanma Oranı</label>
                    @Html.TextBoxFor(x=>x.Value,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Value)
                    <br />
                    <label>Durum</label>
                    @Html.TextBoxFor(x=>x.Status,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Status)
                    <br />
                    <button class="btn btn-success">Ekle</button>

                </form>
            </div>
        </div>
    </div>

}

Core_Proje/Views/Portfolio/EditPortfolio.cshtml
@model EntityLayer.Concrete.Portfolio

@{
    ViewData["Title"] = "EditPortfolio";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("EditPortfolio", "Portfolio", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Proje Düzenleme </p>
                <form class="forms-sample" method="post">
                    @Html.HiddenFor(x=>x.PortfolioId)

                    @Html.Label("Proje Başlığı")
                    @Html.TextBoxFor(x=>x.Name,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Name)
                    <br />
                    <label>Görsel1</label>
                    @Html.TextBoxFor(x=>x.ImageUrl,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ImageUrl)
                    <br />
                    <label>Görsel2</label>
                    @Html.TextBoxFor(x=>x.ImageUrl2,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ImageUrl2)
                    <br />
                    <label>Proje Url</label>
                    @Html.TextBoxFor(x=>x.ProjectUrl,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ProjectUrl)
                    <br />
                    <label>Resim1</label>
                    @Html.TextBoxFor(x=>x.Image1,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image1)
                    <br />
                    <label>Resim2</label>
                    @Html.TextBoxFor(x=>x.Image2,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image2)
                    <br />
                    <label>Resim3</label>
                    @Html.TextBoxFor(x=>x.Image3,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image3)
                    <br />
                    <label>Resim4</label>
                    @Html.TextBoxFor(x=>x.Image4,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image4)
                    <br />
                    <label>Platform</label>
                    @Html.TextBoxFor(x=>x.Platform,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Platform)
                    <br />
                    <label>Tutar</label>
                    @Html.TextBoxFor(x=>x.Price,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Price)
                    <br />
                    <label>Tamamlanma Oranı</label>
                    @Html.TextBoxFor(x=>x.Value,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Value)
                    <br />
                    <label>Durum</label>
                    @Html.TextBoxFor(x=>x.Status,new{@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Status)
                    <br />
                    <button class="btn btn-success">Güncelle</button>

                </form>
            </div>
        </div>
    </div>
}

Core_Proje/Views/Portfolio/Index.cshtml
@using EntityLayer.Concrete
@model List<Portfolio>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

      <div class="row">
        <div class="col">
          <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
              <h3 class="text-white mb-0">Projelerim</h3>
            </div>
            <div class="table-responsive">
              <table class="table align-items-center table-dark table-flush">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col" class="sort" data-sort="name">Proje</th>
                    <th scope="col" class="sort" data-sort="budget">Ücret</th>
                    <th scope="col" class="sort" data-sort="status">Durum</th>
                    <th scope="col">Görseller</th>
                    <th scope="col" class="sort" data-sort="completion">Tamamlanma Oranı</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody class="list">
                    @foreach(var item in Model){
                  <tr>
                    <th scope="row">
                      <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                          <img alt="Image placeholder" src="@item.ImageUrl">
                        </a>
                        <div class="media-body">
                          <span class="name mb-0 text-sm">@item.Name</span>
                        </div>
                      </div>
                    </th>
                    <td class="budget">
                      @item.Price ₺
                    </td>
                    <td>
                      <span class="badge badge-dot mr-4">
                        <i class="bg-success"></i>
                        <span class="status">Tamamlandı</span>
                      </span>
                    </td>
                    <td>
                      <div class="avatar-group">
                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="@item.Name">
                          <img alt="Image placeholder" src="@item.Image1">
                        </a>
                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="@item.Name">
                          <img alt="Image placeholder" src="@item.Image2">
                        </a>
                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="@item.Name">
                          <img alt="Image placeholder" src="@item.Image3">
                        </a>
                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="@item.Name">
                          <img alt="Image placeholder" src="@item.Image4">
                        </a>
                      </div>
                    </td>
                    <td>
                      <div class="d-flex align-items-center">
                        <span class="completion mr-2">@item.Value%</span>
                        <div>
                          <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td><a href="/Portfolio/DeletePortfolio/@item.PortfolioId" class="btn btn-outline-danger">Sil</a></td>
                    <td><a href="/Portfolio/EditPortfolio/@item.PortfolioId" class="btn btn-outline-info">Güncelle</a></td>
                  </tr>
                  }
                </tbody>
              </table>
              <br />
            </div>
          </div>
        </div>
      </div>
                   <a href="/Portfolio/AddPortfolio/" class="btn btn-outline-success">Ekle</a>